a=int(input("enter a number"))
b=int(input("enter b number"))
x=int(input("enter x number"))
print("and:",a&b)
print("or:",a/b)
print("xor:",a^b)
print("not:",~a)
print("x leftshift:",x<<2)
print("y right shift:",x>>2)
