Python 3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
a=5
b=6
c=a+b
>>> 
================= RESTART: C:/Users/dell/Downloads/addition.sql ================
enter the value :6
enter the value :10
add: 16
sub: -4
mul: 60
div: 0.6
fdiv: 0
Traceback (most recent call last):
  File "C:/Users/dell/Downloads/addition.sql", line 14, in <module>
    print("mod:",mod)
NameError: name 'mod' is not defined
>>> 
================= RESTART: C:/Users/dell/Downloads/addition.sql ================
enter the value :3
enter the value :5
add: 8
sub: -2
mul: 15
div: 0.6
fdiv: 0
mod: 3
>>> 
================== RESTART: D:/PROGRAM IN PYTHON/relation.sql ==================
enter the value :5
enter the value :8
Traceback (most recent call last):
  File "D:/PROGRAM IN PYTHON/relation.sql", line 9, in <module>
    print("greater than b:",true)
NameError: name 'true' is not defined. Did you mean: 'True'?
>>> 
================== RESTART: D:/PROGRAM IN PYTHON/relation.sql ==================
enter the value :5
enter the value :7
greater than : False
less than : True
greater than equal to: True
lessthan equal to: False
equal to: True
